In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
matrix, type(matrix)

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 numpy.ndarray)

In [4]:
matrix.shape

(3, 5)

In [5]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ones_array = np.ones((3,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
range_array  = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
identity_matrix = np.eye(3)
identity_matrix, type(identity_matrix)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 numpy.ndarray)

In [9]:
range_array_step = np.arange(5,50,5)
range_array_step

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
range_array_steps = np.arange(2,40,2)
range_array_steps

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [11]:
linspace_array = np.linspace(0,1,5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
linspace_array = np.linspace(0,5,10)
linspace_array, type(linspace_array)

(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]),
 numpy.ndarray)

In [13]:
array = np.array([1,2,3,4,6,5,7,8,9,10])
reshaped_matrix = array.reshape(2,5)
reshaped_matrix

array([[ 1,  2,  3,  4,  6],
       [ 5,  7,  8,  9, 10]])

In [14]:
reshape_matrix = array.reshape(5,2)
reshape_matrix

array([[ 1,  2],
       [ 3,  4],
       [ 6,  5],
       [ 7,  8],
       [ 9, 10]])

In [15]:
flattened_array = array.flatten()
flattened_array

array([ 1,  2,  3,  4,  6,  5,  7,  8,  9, 10])

In [16]:
array_c = np.array([1,2,3,4,5,6,7,8,9,10])
array_c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
flattened_array = array_c.flatten()
array_c 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
flattened_array = array.flatten()
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
flattened_array_min = array.min()
flattened_array_min

1

In [20]:
flattened_array_max = array.max()
flattened_array_max

15

In [21]:
flattened_array_min, flattened_array_max

(1, 15)

In [22]:
array_X = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_X)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
mean_value = array_X.mean()
mean_value

5.5

In [24]:
std_dev = array_X.std()
std_dev

2.8722813232690143

In [25]:
array_1 = np.array([1,2,3,4,5,6,7])
array_2 = np.array([8,9,10,11,12,13,14])
sum_array = array_1 + array_2
sum_array

array([ 9, 11, 13, 15, 17, 19, 21])

In [26]:
array_2 = np.array([1,2,3,4,5,6])
array_3 = np.array([6,5,4,3,2,1])
difference_array = array_3 - array_2
difference_array

array([ 5,  3,  1, -1, -3, -5])

In [27]:
array_4 = np.array([1,2,3,4,5,6,7])
array_5 = np.array([7,6,5,4,3,2,1])
product_array = array_4 * array_5
product_array

array([ 7, 12, 15, 16, 15, 12,  7])

In [28]:
array_6 = np.array([1,2,3,4,5,6,7,8,9])
array_7 = np.array([9,8,7,6,5,4,3,2,1])
divide_array = array_7 / array_6
divide_array

array([9.        , 4.        , 2.33333333, 1.5       , 1.        ,
       0.66666667, 0.42857143, 0.25      , 0.11111111])

In [29]:
array_X = np.array([1,2,3,4,5,6,7])
broadcasted_sum = array_X + 10
broadcasted_sum

array([11, 12, 13, 14, 15, 16, 17])

In [30]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
dot_product = np.dot(matrix1, matrix2)
dot_product

array([[19, 22],
       [43, 50]])

In [31]:
matrix3 = np.array([[1,2],[4,6]])
matrix4 = np.array([[6,4],[2,1]])
dot_product = np.dot(matrix3, matrix4)
dot_product

array([[10,  6],
       [36, 22]])

In [32]:
array = np.array([1,2,3,4,5,6,7,8])
array[4]


5

In [33]:
sub_array = array[1:4]
sub_array

array([2, 3, 4])

In [34]:
matrixX = np.array([[1,2],[3,4]])
matrixX

array([[1, 2],
       [3, 4]])

In [35]:
element_2d = matrixX[1,0]
element_2d

3

In [36]:
element = matrixX[0,1]
element

2

In [37]:
matrix1 = np.array([1,2,3,4,5,6,7,8,9,10])
selected_values = matrix1 > 3
selected_values

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
selectedvalue = matrix1[matrix1 > 3]
selectedvalue

array([ 4,  5,  6,  7,  8,  9, 10])

In [39]:
matrix1[matrix1 > 3] = 99
matrix1

array([ 1,  2,  3, 99, 99, 99, 99, 99, 99, 99])

In [40]:
array_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])